### ISSUE TITLE
About downloading cpp task data

### ISSUE THREAD

**Issue by lzero1115** [tatsy/cpp-python-beginners#1]
This tutorial helped me a lot. By the way I want to know where to download the data about cpp tasks used in your tutorial. Thank you for your work!

**Comment by tatsy** [comment]
Hi @lzero1115, thanks for your interest in my website.
I'm sorry that I cannot remember which data are provided in this website.
Can you tell me which specific data do you need, please? Then, I will put a link to the data.

Thanks!

**Comment by lzero1115** [comment]
Hi, first is the volume cross section data (snail shell) in the Marching Cubes tasks. Then is the Point Cloud data used for ICP task. Finally is the point cloud data (Buddha statue) for mesh reconstruction task. The three above data are not provided in this project. Appreciate for your nice work.

**Comment by lzero1115** [comment]
@tatsy If the data is not conveniently made public, please tell me some data that could be used instead for testing.

**Comment by tatsy** [comment]
@lzero1115 Sorry to respond you too late. I have added the data files on the webpage. The URL is as below.
https://drive.google.com/drive/folders/11yHeeVfKmjxel_7d3k9aUIob7DRuhB_H?usp=sharing
